### ISSUE TITLE
Clarify licensing

### ISSUE THREAD

**Issue by jansegre** [selfthinker/CSS-Playing-Cards#8]
I haven't found an explicit license for usage of this project.

The [comparison](http://socialcompare.com/en/comparison/css-playing-cards-pgnq7dx) linked on the main page says this is CC-BY-SA, the README on faces says the images there are LGPL.

I think a simple statement on the README would do, the most permissive would be [CC0](https://creativecommons.org/publicdomain/zero/1.0/) if that's intended, [CC-BY-SA 3.0](https://creativecommons.org/licenses/by-sa/3.0/) would be a reasonable choice, but without any license I think all rights reserved have to be assumed.

**Comment by selfthinker** [comment]
The README clearly says it's CC BY-SA. The other README in the faces folder states a different license because that is the license purely for those images.

**Comment by jansegre** [comment]
Oops, my bad! I wonder how did I miss that, I thought I ctrl+f'd for "license" first, maybe I just looked for a license/copying section.
